# Generated by Django 5.2.5 on 2025-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
